/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as InternationalRouteImport } from './routes/international'
import { Route as OccasionsRouteImport } from './routes/occasions'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as FleetIndexRouteImport } from './routes/fleet.index'
import { Route as FleetSlugRouteImport } from './routes/fleet.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalRoute = InternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsRoute = OccasionsRouteImport.update({
  id: '/occasions',
  path: '/occasions',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetIndexRoute = FleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetSlugRoute = FleetSlugRouteImport.update({
  id: '/fleet/$slug',
  path: '/fleet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/international': typeof InternationalRoute
  '/occasions': typeof OccasionsRoute
  '/partners': typeof PartnersRoute
  '/requirements': typeof RequirementsRoute
  '/fleet/$slug': typeof FleetSlugRoute
  '/fleet/': typeof FleetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/international': typeof InternationalRoute
  '/occasions': typeof OccasionsRoute
  '/partners': typeof PartnersRoute
  '/requirements': typeof RequirementsRoute
  '/fleet/$slug': typeof FleetSlugRoute
  '/fleet': typeof FleetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/international': typeof InternationalRoute
  '/occasions': typeof OccasionsRoute
  '/partners': typeof PartnersRoute
  '/requirements': typeof RequirementsRoute
  '/fleet/$slug': typeof FleetSlugRoute
  '/fleet/': typeof FleetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/corporate'
    | '/international'
    | '/occasions'
    | '/partners'
    | '/requirements'
    | '/fleet/$slug'
    | '/fleet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/corporate'
    | '/international'
    | '/occasions'
    | '/partners'
    | '/requirements'
    | '/fleet/$slug'
    | '/fleet'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/corporate'
    | '/international'
    | '/occasions'
    | '/partners'
    | '/requirements'
    | '/fleet/$slug'
    | '/fleet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  InternationalRoute: typeof InternationalRoute
  OccasionsRoute: typeof OccasionsRoute
  PartnersRoute: typeof PartnersRoute
  RequirementsRoute: typeof RequirementsRoute
  FleetSlugRoute: typeof FleetSlugRoute
  FleetIndexRoute: typeof FleetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international': {
      id: '/international'
      path: '/international'
      fullPath: '/international'
      preLoaderRoute: typeof InternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions': {
      id: '/occasions'
      path: '/occasions'
      fullPath: '/occasions'
      preLoaderRoute: typeof OccasionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/': {
      id: '/fleet/'
      path: '/fleet'
      fullPath: '/fleet/'
      preLoaderRoute: typeof FleetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/$slug': {
      id: '/fleet/$slug'
      path: '/fleet/$slug'
      fullPath: '/fleet/$slug'
      preLoaderRoute: typeof FleetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  InternationalRoute: InternationalRoute,
  OccasionsRoute: OccasionsRoute,
  PartnersRoute: PartnersRoute,
  RequirementsRoute: RequirementsRoute,
  FleetSlugRoute: FleetSlugRoute,
  FleetIndexRoute: FleetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
